before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: incipher
      name: homebrew-tap
    homepage: https://incipher.io/shamir
    description: "Split and combine secrets using Shamir's Secret Sharing algorithm."
    license: CC0
    url_template: 'https://github.com/incipher/shamir/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    test: |
      system "#{bin}/shamir --version"
    skip_upload: true
